[project]
name = "StacksOrbit"
clarinet_version = "3.12.0"
epoch = "3.0"

[accounts]
deployer = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"

[simnet]
mnemonic = "cute bird surprise boring old news cake design aisle helmet choose tree"

[contracts.placeholder]
path = "contracts/placeholder.clar"

[contracts.revenue-automation]
path = "contracts/revenue-automation.clar"

[contracts.dlc-orchestrator]
path = "contracts/dlc-orchestrator.clar"

[contracts.dlc-bond]
path = "contracts/dlc-bond.clar"

[contracts.sip-010-ft-trait]
path = "contracts/sip-standards/sip-010-ft-trait.clar"
