[project]
name = "test-conxian"
description = "Test project for auto-detection"

[contracts.all-traits]
path = "contracts/traits/all-traits.clar"

[contracts.cxd-token]
path = "contracts/tokens/cxd-token.clar"

[contracts.dex-factory]
path = "contracts/dex/dex-factory.clar"

[contracts.dim-registry]
path = "contracts/dimensional/dim-registry.clar"

[contracts.oracle-aggregator]
path = "contracts/oracle/oracle-aggregator.clar"
