name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: CI on ${{ matrix.os }} | Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,test]

      - name: Install Node deps
        run: npm install

      - name: Lint (JS + Python)
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: GUI smoke test
        run: npm run test:gui

      - name: Upload coverage (optional)
        if: matrix.os == 'ubuntu-latest' && hashFiles('coverage.xml') != ''
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
          fail_ci_if_error: false
